use serde::Deserialize;

use crate::sites::Sites;

#[derive(Clone, Debug, Default, Deserialize)]
pub enum Currency {
    XRP,
    DECOY,
    USDT,
    #[default]
    BTC,
    LTC,
    TRX,
    DOGE,
    ETH,
    XLM,
    BCH,
    BNB,
    SHIB,
    USDC,
    ADA,
    DASH,
    SOL,
    ATOM,
    ETC,
    XMR,
    EOS,
    BTTC,
    POL,
    DOT,
    ZEC,
    RVN,
    LINK,
    DAI,
    TUSD,
    AVAX,
    NEAR,
    ZEN,
    AAVE,
    NOT,
    ENA,
    UNI,
    TON,
    TRUMP,
    FDUSD,
    WBTC,
    CAD,
}

impl Currency {
    pub fn get_min_bet(&self, site: Sites) -> f32 {
        match site {
            Sites::DuckDiceIo => match self {
                Self::XRP => 0.001,
                Self::DECOY => 0.01,
                Self::USDT => 0.002,
                Self::BTC => 0.00000001,
                Self::LTC => 0.00002,
                Self::TRX => 0.006,
                Self::DOGE => 0.01,
                Self::ETH => 0.0000005,
                Self::XLM => 0.005,
                Self::BCH => 0.000005,
                Self::BNB => 0.000002,
                Self::SHIB => 100.,
                Self::USDC => 0.002,
                Self::ADA => 0.002,
                Self::DASH => 0.0001,
                Self::SOL => 0.000008,
                Self::ATOM => 0.0004,
                Self::ETC => 0.00012,
                Self::XMR => 0.000006,
                Self::EOS => 0.002,
                Self::BTTC => 2000.,
                Self::POL => 0.01,
                Self::DOT => 0.0005,
                Self::ZEC => 0.00004,
                Self::RVN => 0.01,
                Self::LINK => 0.0001,
                Self::DAI => 0.002,
                Self::TUSD => 0.002,
                Self::AVAX => 0.0001,
                Self::NEAR => 0.0008,
                Self::ZEN => 0.0002,
                Self::AAVE => 0.000006,
                Self::NOT => 0.8,
                Self::ENA => 0.006,
                Self::UNI => 0.0003,
                Self::TON => 0.0006,
                Self::TRUMP => 0.0002,
                Self::FDUSD => 0.002,
                Self::WBTC => 0.00000004,
                Self::CAD => 0.01,
            },
            _ => 1e-8,
        }
    }
}

impl std::fmt::Display for Currency {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let currency_str = match self {
            Self::XRP => "XRP",
            Self::DECOY => "DECOY",
            Self::USDT => "USDT",
            Self::BTC => "BTC",
            Self::LTC => "LTC",
            Self::TRX => "TRX",
            Self::DOGE => "DOGE",
            Self::ETH => "ETH",
            Self::XLM => "XLM",
            Self::BCH => "BCH",
            Self::BNB => "BNB",
            Self::SHIB => "SHIB",
            Self::USDC => "USDC",
            Self::ADA => "ADA",
            Self::DASH => "DASH",
            Self::SOL => "SOL",
            Self::ATOM => "ATOM",
            Self::ETC => "ETC",
            Self::XMR => "XMR",
            Self::EOS => "EOS",
            Self::BTTC => "BTTC",
            Self::POL => "POL",
            Self::DOT => "DOT",
            Self::ZEC => "ZEC",
            Self::RVN => "RVN",
            Self::LINK => "LINK",
            Self::DAI => "DAI",
            Self::TUSD => "TUSD",
            Self::AVAX => "AVAX",
            Self::NEAR => "NEAR",
            Self::ZEN => "ZEN",
            Self::AAVE => "AAVE",
            Self::NOT => "NOT",
            Self::ENA => "ENA",
            Self::UNI => "UNI",
            Self::TON => "TON",
            Self::TRUMP => "TRUMP",
            Self::FDUSD => "FDUSD",
            Self::WBTC => "WBTC",
            Self::CAD => "CAD",
        };
        write!(f, "{}", currency_str)
    }
}
